[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "openssl", "pkg-config"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "python main.py"
